{{- if not .Values.dynamo.enabled }}
apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: DynamoDb
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  name: {{ include "chart.fullname" . }}
{{- end }}
