apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "chart.fullname" . }}-vs
spec:
  hosts:
  - "*"
  gateways:
  - cory.my-gateway
  http:
  - match:
    - uri:
        prefix: /domain-service
    route:
    - destination:
        port:
          number: 80
        host: {{ include "chart.fullname" . }}