name: Deploy Feature Branch

on:
  workflow_dispatch:
    branches: ['feature/*']

jobs:
  deploy:
    env:
      SERVICE_KEY: domain-service
      REGION: us-west-2
      CLUSTER: hackathon-microservices
      NAMESPACE: test
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract normalized branch
        shell: bash
        run: |
          raw=${GITHUB_REF#refs/heads/}
          no_slash=${raw//\//-}
          clean=${no_slash//_/-}
          echo "::set-output name=branch::$clean"
        id: extract_branch

      - uses: elationemr/github-actions/deployment/build-and-push-to-ecr@main
        id: build-and-push-image
        with:
          ecr-repository: ${{ env.SERVICE_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Configure CI credentials
        id: configure_init_creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      
      - name: Configure Kubectl
        id: configure_kubectl
        run: |
          aws eks --region ${{ env.REGION }} update-kubeconfig --name ${{ env.CLUSTER }}
          echo "::set-output name=kubeconfig::$(cat ~/.kube/config)"

      - name: Helm install
        id: helm_install
        working-directory: chart
        run: helm install ${{ steps.extract_branch.outputs.branch }} . -n ${{ env.NAMESPACE }} --set image.tag=${{ steps.extract_branch.outputs.branch }}

