name: Teardown Feature Environment

on:
  pull_request:
    types: [closed]

jobs:
  teardown:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      SERVICE_KEY: domain-service
      REGION: us-west-2
      CLUSTER: hackathon-microservices
    name: Teardown Feature Environment
    steps:
      - uses: actions/checkout@v2

      - name: Get namespace
        shell: bash
        run: |
          raw="${{ github.head_ref }}"
          no_slash=${raw//\//-}
          clean=${no_slash//_/-}
          namespace=${{ env.SERVICE_KEY }}-${{ steps.extract_branch.outputs.branch }}
          echo "::set-output name=namespace::$namespace"
        id: get_namespace

      - name: Configure CI credentials
        id: configure_init_creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      
      - name: Delete Namespace
        id: delete_namespace
        run: |
          aws eks --region ${{ env.REGION }} update-kubeconfig --name ${{ env.CLUSTER }}
          kubectl delete namespace ${{ steps.get_namespace.outputs.namespace }}
          echo "::set-output name=kubeconfig::$(cat ~/.kube/config)"
