name: Teardown Feature Environment

on:
  pull_request:
    types: [closed]

jobs:
  teardown:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      SERVICE_KEY: domain-service
      REGION: us-west-2
      CLUSTER: hackathon-microservices
    name: Teardown Feature Environment
    steps:
      - uses: actions/checkout@v2

      - name: Extract normalized branch
        shell: bash
        run: |
          raw="${{ github.head_ref }}""
          no_slash=${raw//\//-}
          clean=${no_slash//_/-}
          echo "::set-output name=branch::$clean"
        id: extract_branch

      - name: Show branch name
        run: echo ${{ steps.extract_branch.outputs.branch }}
